src/SkinDesign/Entities/Procedure.cs
using System.ComponentModel.DataAnnotations;

namespace SkinDesign.Entities
{
    public class Procedure
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

src/SkinDesign/Entities/User.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace SkinDesign.Entities
{
    public class User : IdentityUser
    {
    }
}

src/SkinDesign/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SkinDesign.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required, DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }
}

src/SkinDesign/ViewModels/ProcedureViewModel.cs
namespace SkinDesign.ViewModels
{
    public class ProcedureViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

src/SkinDesign/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkinDesign.Entities;
using SkinDesign.ViewModels;
using System.Threading.Tasks;

namespace SkinDesign.Controllers
{
    public class AccountController : Controller
    {
        private SignInManager<User> _signInManager;
        private UserManager<User> _userManager;

        public AccountController(UserManager<User> userManger, SignInManager<User> signInManager)
        {
            _userManager = userManger;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var loginResult = await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false);

                if (loginResult.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            ModelState.AddModelError("", "Could not login.");
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/SkinDesign/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SkinDesign.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }
    }
}

src/SkinDesign/Controllers/ProceduresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkinDesign.Entities;
using SkinDesign.Interfaces;
using SkinDesign.ViewModels;
using System.Linq;

namespace SkinDesign.Controllers
{
    public class ProceduresController : Controller
    {
        private IProceduresData _data;

        public ProceduresController(IProceduresData data)
        {
            _data = data;
        }

        public IActionResult All()
        {
            var model = _data.GetAll().ToList();

            return View(model);
        }

        public IActionResult Procedure(int id)
        {
            var model = _data.GetById(id);

            if(model == null)
            {
                return RedirectToAction(nameof(ProcedureNotFound));
            }

            return View(model);
        }

        public IActionResult ProcedureNotFound()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddProcedure()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddProcedure(ProcedureViewModel model)
        {
            if(ModelState.IsValid)
            {
                var newProcedure = new Procedure();
                newProcedure.Name = model.Name;
                newProcedure.Description = model.Description;

                _data.Add(newProcedure);

                return RedirectToAction(nameof(All));
            }

            return View(model);
            
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            _data.Delete(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            var procedure = _data.GetById(id);
            if(procedure == null)
            {
                return RedirectToAction(nameof(ProcedureNotFound));
            }

            return View(procedure);
        }

        [HttpPost]
        public IActionResult Edit(ProcedureViewModel model, int id)
        {
            if(ModelState.IsValid)
            {
                var procedure = _data.GetById(id);
                if(procedure == null)
                {
                    return RedirectToAction(nameof(ProcedureNotFound));
                }

                procedure.Name = model.Name;
                procedure.Description = model.Description;
                _data.Save();

                return View(nameof(Procedure), procedure);
            }

            return View(model);
            
        }
    }
}

src/SkinDesign/ViewComponets/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SkinDesign.ViewComponets
{
    public class NavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/SkinDesign/Views/Home/Contacts.cshtml
@{ 
    ViewBag.Title = "Contacts";
}
<div class="row">
    <div class="well col-md-6">
        <h2>Козметичен салон Skin Design</h2>
        <div>
            <h3><i class="fa fa-home fa-fw home-icon" aria-hidden="true"></i> Адрес:</h3>
            <span class="text-info">София, ул. Св. Иван Рилски №15, ет. 2</span>
        </div>
        <div>
            <h3><i class="fa fa-phone fa-fw phone-icon" aria-hidden="true"></i> Телефон:</h3>
            <span class="text-info">0879 88 88 52</span>
        </div>
        <div>
            <h3><i class="fa fa-envelope fa-fw email-icon" aria-hidden="true"></i> Имейл:</h3>
            <span class="text-info">studio.skin.design@gmail.com</span>
        </div>
    </div>
    <div class="col-md-6">
        <iframe width="600"
                height="450"
                frameborder="0"
                style="border:0"
                src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJW0u0IRSFqkARrt0KNm_W70A&key=AIzaSyDuru0p71olYMllMaBrT3ZbMTPmRobE2j0"
                allowfullscreen></iframe>
    </div>
</div>

src/SkinDesign/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Home";
}

<div class="image home-image"></div>

src/SkinDesign/Views/Procedures/AddProcedure.cshtml
@model ProcedureViewModel

@{ 
    ViewBag.Title = "Add procedure";
}

<div class="col-md-6 col-md-offset-3">
    <div class="well">
        <form method="post" asp-antiforgery="true" class="form-horizontal">
            <h3>Добавете процедура</h3>
            <div class="control-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="control-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="text-right add-btn">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>

src/SkinDesign/Views/Procedures/All.cshtml
@model IEnumerable<Procedure>

@{ 
    ViewBag.Title = "All procedures";
}

<h1>
    <span class="text-info">Процедури</span>
    @if (User.Identity.IsAuthenticated)
    {
        <a class="btn btn-default pull-right" asp-action="AddProcedure">Добави процедура</a>
    }
</h1>

@foreach (var procedure in Model)
{
    @Html.Partial("_Summary", procedure)
}

src/SkinDesign/Views/Procedures/Edit.cshtml
@model Procedure

@{ 
    ViewBag.Title = "Edit";
}
<div class="form-horizontal col-md-6 col-md-offset-3">
    <div class="well">
        <form method="post" asp-antiforgery="true" asp-route-id="@Model.Id" class="form-horizontal">
            <h3>Променяне процедура</h3>
            <div class="control-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="control-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="text-right edit-btn">
                <input type="submit" class="btn btn-primary" value="Edit" />
            </div>
        </form>
    </div>
</div>

src/SkinDesign/Views/Procedures/Procedure.cshtml
@model Procedure

@{ 
    ViewBag.Title = "Procedure";
}

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">@Model.Description</div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="panel-footer">
            <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id">Промени</a>
            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Изтрий</a>
        </div>
    }
    
</section>

src/SkinDesign/Views/Procedures/ProcedureNotFound.cshtml
@{ 
    ViewBag.Title = "Not found";
}

<div class="col-md-4 col-md-offset-4">
    <h3>Несъществуваща процедура</h3>
</div>

src/SkinDesign/Views/Procedures/_Summary.cshtml
@model Procedure

<section class="panel panel-default">
    <h3 class="panel-heading"><a asp-action="Procedure" asp-route-id="@Model.Id">@Model.Name</a></h3>
    <div class="panel-body">@Model.Description</div>
</section>

src/SkinDesign/Views/Shared/Components/Navigation/Default.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Skin Design</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Procedures" asp-action="All">Procedures</a></li>
                <li><a asp-controller="Home" asp-action="Contacts">Contacts</a></li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="nav navbar-nav navbar-right">
                    <span class="navbar-text">Hello, @User.Identity.Name</span>
                    <a asp-controller="Account" asp-action="Logout" class="btn btn-default navbar-btn">Logout</a>
                </div>
            }
        </div>
    </div>
</nav>

src/SkinDesign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Skin Design - @ViewBag.Title</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/node_modules/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div>
        @await Component.InvokeAsync("Navigation")
    </div>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>